### PR TITLE
chore: introduce a fix for release-please not firing on PR workflows

### PR DESCRIPTION
**Pull request by Racer159**
Testing to see if this is a viable workaround for release-please PRs.

### CODE REVIEW

**Review by Racer159 — COMMENTED** [review]
submitting a review!

**Comment by zachariahmiller** [comment]
@Racer159  I dont think the condition matters. This doesnt work by design. The solution is using a github app. 

Happy to facilitate the test though, what do you need here?

**Comment by mjnagel** [comment]
@zachariahmiller the hope was that the workflow would trigger because a real person is doing the milestone action I think vs the github_token adding it somehow. The current issue is that the workflow doesn't trigger on a push from the github_token, but suspicion/hope was that some other trigger (milestone in this case) would work, as long as the actor is not github_token. Might be a flawed assumption there, but most places this issue is listed specifically callout pushes from the github_token being the problem.

**Comment by zachariahmiller** [comment]
Got it. Yeah... Happy to be wrong, but I think this would have been an identified workaround if it worked. Could we test this somewhere that is not actually used for things? 😅

I still think the correct solution to this and all similar problems is the GitHub app. It is unclear to me why we aren't just pressing to get that created.

**Comment by mjnagel** [comment]
Confirmed this works on https://github.com/mjnagel/test/pull/48, with a release-please created PR.

**Review by mjnagel — APPROVED** [review]

**Pull request merged**
